name: BVR
favicon: null
layout_spectrum: 0.32423
typography_spectrum: 0.47275
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#071c2d'
    - '#9aa3aa'
    - '#5b6872'
    - '#c3c5c6'
  brandStrength: 1
  lightness: 0.334380398504436
  saturation: 0.644392600050196
  rhythmicContrast: 0.23926370847038925
purpose: []
