name: BVR
favicon: null
layout_spectrum: 0.34023079299367964
typography_spectrum: 0.38275162037461996
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.10250894608907402
  lightness: 0.334380398504436
  saturation: 0.644392600050196
  rhythmicContrast: 0.23926370847038925
purpose: []
